src/BaseSettings/urls.py
from django.conf.urls import url ,include

from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('Users/', include(('Users.urls','Users'), namespace='Users')),
    path('',include('SmsBaseApp.urls')),
    path('Team/' , include('Team.urls')),
    path('SmsBackEnd/', include(('SmsBackEnd.urls','SmsBackEnd'), namespace='SmsBackEnd')),
]

src/Team/urls.py
from django.urls import include, path, re_path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views_attachment import *
from .views_member import *
from .views_permission import *
from .views import *

app_name = "Team"
# set name url with function in views  manage user
urlpatterns = [
    path("show_team_all/", show_team_all, name="show_team_all"),
    path("show_team_page/", show_team_page, name="show_team_page"),
    path("create_team/", create_team_page, name="create_team"),
    path("create_team_save/", create_team, name="create_team_save"),
    path("add_member_page/", add_member_page, name="add_member_page"),
    path("add_member/", add_member, name="add_member"),
    path(
        "delete_member_from_id_role/",
        delete_member_from_id_role,
        name="delete_member_from_id_role",
    ),
    path(
        "show_member_list_by_team/",
        show_member_list_by_team,
        name="show_member_list_by_team",
    ),
    path("add_attachment_page/", add_attachment_page, name="add_attachment_page"),
    path("add_attachment/", add_attachment, name="add_attachment"),
    path("show_attachments/", show_attachments, name="show_attachments"),
    path("delete_attachment/", delete_attachment, name="delete_attachment"),
    path("add_permission_page/", add_permission_page, name="add_permission_page"),
    path("add_permission/", add_permission, name="add_permission"),
    path("show_permissions/", show_permissions, name="show_permissions"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

src/Users/urls.py
from django.urls import include, path,re_path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views_users_admin import *
app_name = 'Users'

#set name url with function in views  manage user

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('status_message/', status_message, name='status_message'),
    path('admin_create_user_page/', admin_create_user_page, name='admin_create_user_page'),
    path('admin_create_user/', create_new_user, name='create_new_user'),
    path('user_all/', user_all, name='user_all'),

    re_path(r'^user/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate_account, name='activate_account'),
    re_path(r'^user/reset/password/request/$', password_reset_request,name='password_reset_request'),
    re_path(r'^user/reset/password/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<date>[0-9A-Za-z_\-]+)/(?P<time>[0-9A-Za-z_\-]+)/$',activate_password_reset, name='activate_password_reset'),
    re_path(r'^user/reset/password/change/$', reset_change_password_request,name='reset_change_password'),
    re_path(r'^user/change_password/$', change_password,name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

src/Users/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.sessions.models import Session
from Team.models import TeamModel


class Permission(models.Model):
    id_permission = models.AutoField(primary_key=True)
    name_permission = models.CharField(max_length=255, unique=True)


class Attachment(models.Model):
    id_attachment = models.AutoField(primary_key=True, unique=True)
    name_attachment = models.CharField(max_length=255, unique=True)
    id_permission = models.ForeignKey(Permission, null=False, on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="images/", default="media/photos/image.jpg")
    bio = models.TextField(max_length=500, null=True, blank=True)
    tel = models.CharField(max_length=15, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    employeeID = models.CharField(max_length=255, blank=True)


class UserSession(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    last_login = models.DateTimeField(null=True, blank=True)


class Role_user(models.Model):
    id_role = models.AutoField(primary_key=True)
    id_team = models.ForeignKey(TeamModel, null=False, on_delete=models.CASCADE)
    id_user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    id_attachment = models.ForeignKey(Attachment, null=False, on_delete=models.CASCADE)


src/Users/views.py
from django.contrib.auth import login as dj_login, logout as dj_logout
from django.contrib.auth.signals import user_logged_in
from .models import UserSession
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.conf import settings
from django.core.mail import EmailMessage
import os.path
from .forms import SignUpForm, LoginForm
from rolepermissions.roles import assign_role
from SmsBackEnd.helper import date_format, encode, decode
from datetime import datetime
# import datetime
from django.utils.translation import ugettext_lazy as _
from .forms import SignUpForm,AdminSignUpForm, LoginForm, PasswordResetRequestForm, ResetChangePasswordForm, ChangePasswordForm
from django.contrib.auth.models import Group
projectPath = '/Users'
homePath = '/'
superadminPath = '/SmsBackEnd/ibiobank_admin/'
adminPath = '/SmsBackEnd/equipment_admin/'
loPath = '/SmsBackEnd/equipment_Lo/'
BoosterPath = '/SmsBackEnd/equipment_Booster/'
StudentPath = '/SmsBackEnd/equipment_Student/'
loginPath = '/Users/login/'


# Signup function
def signup(request):
    args = {}
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        # Check register button
        if 'registerbtn' in request.POST:
            print("test")
            if form.is_valid():
            #     user = form.save()
            #     user = User.objects.filter(username=form.cleaned_data.get('username')).first()
            #     group = Group.objects.get(name='user')
            #     user.groups.add(group)

            #     # email confirmation
            #     current_site = get_current_site(request)
            #     subject = _('Confirm registration from SmsBaseApp')
            #     message = render_to_string('acc_active_email.html', {
            #         'user': user,
            #         'domain': current_site,
            #         'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #         'token': account_activation_token.make_token(user),
            #     })
            #     # user.email_user(subject, message) #request User Activate
            #     # assign_role(user, 'doctor')
            #     email = EmailMessage(subject, message, to=['wanattapong1997@gmail.com']) #ส่งไปที่ Email Admin
            #     email.send()
            #     message_header =_('สมัคร สำเร็จ.')
            #     message_detail =_('กรุณาเข้ารับการฝึกอบรม.')
            #     message_header_json = str(message_header)
            #     message_detail_json = str(message_detail)
            #     request.session['sm_value'] = {'message_header': message_header_json,
            #                                    'message_detail': message_detail_json,
            #                                    'type': 'success',
            #                                    'displaytime': '10'}
            #     request.session['goto'] = loginPath

                return redirect(projectPath+'/status_message/')

            else:
                print(form.errors.as_data())

    else:
        # if not post show form signup
        form = SignUpForm()

    args['form'] = form
    return render(request, 'signup.html', args)


def staff_is(staffId):
    if staffId is not False:
        try:
            group = Group.objects.get(id=staffId)
            return group.name
        except Exception as e:
            print(e)
            return False
    return False
# Login function
def login(request):
    if staff_is(request.user.is_staff):
        g = staff_is(request.user.is_staff)
        print(g)
        if str(g) == "Admin":
            return redirect("Team:create_team")
    user_session = ''
    args = {}
    form = LoginForm(request.POST or None)

    # check if post button login check user pass
    if request.method == 'POST':
        if 'loginBtn' in request.POST and form.is_valid():

            user = form.login(request)

            request.session['user_id'] = user.id
            # check new user create storage folder
            check_create_storage(request)
            if user is not None:
                dj_login(request, user)
                print('----------------------------')
                user_logged_in_handler('joe',request,user)
                
                # if 'next' in request.POST:
                #     return redirect(request.POST.get('next'))
                if is_user(request , user):
                    return redirect(homePath) 
                elif is_superadmin(request, user):
                    return redirect(superadminPath)   
                elif is_admin(request, user):
                    return redirect(adminPath) 
                elif is_Lo(request, user):
                    return redirect(loPath) 
                elif is_Booster(request, user):
                    return redirect(BoosterPath) 
                elif is_Student(request, user):
                    return redirect(StudentPath) 
                
                return redirect(homePath)
            
        elif 'test' in request.POST:
            message_header =_('Register successfully.')
            message_detail =_('Please confirm your email.')
            message_header_json = str(message_header)
            message_detail_json = str(message_detail)
            request.session['sm_value'] = {'message_header': message_header_json,
                                           'message_detail': message_detail_json,
                                           'type': 'success',
                                           'displaytime': '10'}
            


            return redirect(projectPath + '/status_message/')  


    args['form'] = form
    return render(request, 'login.html', args)


def is_user(request,user):
    request.session.modified = True
    request.session['user_session'] = "user" 
    if user.groups.filter(name='user').exists(): 
        return True
    else:
        return False   

def is_superadmin(request,user):
    request.session.modified = True
    request.session['user_session'] = "Administrator"
    if user.groups.filter(name='Administrator').exists():  
        return True
    else:
        return False

def is_admin(request,user):
    request.session.modified = True
    request.session['user_session'] = "Admin"
    if user.groups.filter(name='Admin').exists():  
        return True
    else:
        return False

def is_Lo(request,user):
    request.session.modified = True
    request.session['user_session'] = "Lo"
    if user.groups.filter(name='Lo').exists():  
        return True
    else:
        return False

def is_Student(request,user):
    request.session.modified = True
    request.session['user_session'] = "Student"
    if user.groups.filter(name='Student').exists():  
        return True
    else:
        return False

def is_Booster(request,user):
    request.session.modified = True
    request.session['user_session'] = "Booster"
    if user.groups.filter(name='Booster').exists():  
        return True
    else:
        return False



def activate_account(request, uidb64, token):

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        #dj_login(request, user)
        message_header =_('Confirm email successfully.')
        message_detail =_('Enjoy using our system.')
        message_header_json = str(message_header)
        message_detail_json = str(message_detail)
        request.session['sm_value'] = {'message_header': message_header_json,
                                       'message_detail': message_detail_json,
                                       'type': 'success',
                                       'displaytime': '10'}
        request.session['goto'] = loginPath

        return redirect(projectPath+'/status_message/')
    else:
        message_header =_('Confirm email failed.')
        message_detail =_('Please contact officer.')
        message_header_json = str(message_header)
        message_detail_json = str(message_detail)
        request.session['sm_value'] = {'message_header': message_header_json,
                                       'message_detail': message_detail_json,
                                       'type': 'error',
                                       'displaytime': '10'}

        request.session['goto'] = homePath


        return redirect(projectPath+'/status_message/')



# Check and Create folder
def check_create_storage(request):

    try:
        user_id = request.session.get('user_id')
        path = str(user_id)
        default_path = os.path.abspath(settings.MEDIA_ROOT+"/storage/"+path)
        if not os.path.exists(settings.MEDIA_ROOT+"/storage/"+path):
            os.makedirs(default_path)
    except OSError as e:
        if e.errno == 17:
            return False




def status_message(request):
    args = {}

    try:
        args['goto'] = request.session['goto']
        sm_value = request.session['sm_value']
        args['type'] = sm_value['type']
        args['message_header'] = sm_value['message_header']
        args['message_detail'] = sm_value['message_detail']
        args['displaytime'] = sm_value['displaytime']

        del request.session['goto']
        del request.session['sm_value']


src/Users/templates/acc_active_email.html
{% autoescape off %}
{% load i18n %}
{% trans "Hello" %} {{ user.get_full_name }},
{% trans "Click link to comfirm" %} ,
http://{{ domain }}{% url 'Users:activate_account' uidb64=uid token=token %}
{% endautoescape %}

src/Users/templates/acc_reset_password_email.html
{% load i18n %}
{% autoescape off %}
    {% trans "Hello" %} {{ user.get_full_name }},
    {% trans "Click link to confirm a password" %},
    http://{{ domain }}{% url 'Users:activate_password_reset' uidb64=uid token=token date=date time=time %}


    {% trans "Note: The 30 minute expired then make a new request." %} 
{% endautoescape %}

src/Users/templates/admin_signup.html
{% extends "includes/base_user.html" %}
{% load i18n %}
{% load static %}
{% block document_container %}
<div class="container">
<div class="row justify-content-md-center">
    <div class="col-md-4 col-md-auto">
            <img src="{% static 'img/content/logo.png' %}">
    </div>
</div>
<div class="row">
   <div class="col-md-6 offset-md-3">


<!-- Default form register -->
<form class="text-center border border-light p-5" method="post">
     {% csrf_token %}
                        {% for field in form %}
                        <p>
                            {% if forloop.counter == 1 %}
                        <p class="text-left">Select a username and password admin</p>
                        <hr>
                        {% endif%}
                        {% if forloop.counter == 5 %}
                        <p class="text-left">Contact information</p>
                        <hr>
                        {% endif%}
                        {% if forloop.counter == 6 %}

                        <p class="text-left">In case your forget your password </p>
                        <hr>
                        {% endif%}
                        {{ field }}
                        {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                        </p>
                        {% endfor %}

    <!-- Sign up button -->
    <button class="btn btn-info my-4 btn-block" name="registerbtn" type="submit">Sign in</button>

    <!-- Social register -->
    <p>or sign up with:</p>

    <a  class="light-blue-text mx-2">
        <i class="fa fa-facebook"></i>
    </a>
    <a class="light-blue-text mx-2">
        <i class="fa fa-twitter"></i>
    </a>
    <a class="light-blue-text mx-2">
        <i class="fa fa-linkedin"></i>
    </a>
    <a  class="light-blue-text mx-2">
        <i class="fa fa-github"></i>
    </a>

    <hr>

    <!-- Terms of service -->
    <p>By clicking
        <em>Sign up</em> you agree to our
        <a href="" target="_blank">terms of service</a> and
        <a href="" target="_blank">terms of service</a>. </p>

</form>
<!-- Default form register -->

    </div>
</div>
</div>

{% endblock document_container %}

src/Users/templates/change_password.html
{% extends "includes/base_user.html" %} {% load i18n %} {% load static %} {% block document_container %}
    <h2 class="ui dividing header">{% trans "Set new password" %}</h2>

    <form method="post">
        {% csrf_token %}
        <div class="ui two column middle aligned very relaxed stackable grid">
            <div class="column">
                <div class="ui form">
                    <div class="field"> 
                        <label>{% trans "Old Password" %}</label>
                        <div class="ui left icon input">
                            {{ form.password0 }}
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    <div class="field">
                        <label>{% trans "New Password" %}</label>
                        <div class="ui left icon input">
                            {{ form.password1 }}
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    <div class="field">
                        <label>{% trans "Confirm Password" %}</label>
                        <div class="ui left icon input">
                            {{ form.password2 }}
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="ui red message">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                    <button class="ui blue submit button" name="cpBtn" type="submit">{% trans "Submit" %}</button>
                    <a href="{% url 'Users:login'%}"><div class="ui button">{% trans "Cancel" %}</div></a>
                </div>
            </div>
        </div>
    </form>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


{% endblock document_container %}

src/Users/templates/login.html
{% extends "includes/base_user.html" %}
<!--  -->
{% load i18n %} {% load static %}
<!--  -->
{% block content %}
<br /><br />
<!-- <div class="container"> -->
<div class="row">
  <div class="col-md-6 offset-md-3">
    <!-- Default form login -->
    <form
      class="text-center border border-light p-5"
      style="background: white;"
      method="post"
    >
      {% csrf_token %}
      <p class="h4 mb-4">{% trans "Sign in" %}</p>

      {% if request.GET.next %}
      <input
        type="hidden"
        name="next"
        class="form-control"
        value="{{ request.GET.next }}"
      />
      {% endif %} {{form.username}} {{ form.password }}
      <!--  -->
      {% if form.non_field_errors %}
      <!--  -->
      {% for error in form.non_field_errors %}
      <div class="ui red message">{{ error }}</div>
      {% endfor %}
      <!--  -->
      {% endif %}

      <!--<div class="d-flex justify-content-around">-->
      <!--<div>-->
      <!--&lt;!&ndash; Remember me &ndash;&gt;-->
      <!--<div class="custom-control custom-checkbox">-->
      <!--<input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">-->
      <!--<label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>-->
      <!--</div>-->
      <!--</div>-->
      <!--<div>-->
      <!--&lt;!&ndash; Forgot password &ndash;&gt;-->
      <!--</a> /<a href="{% url 'Users:password_reset_request'%}">-->
      <!--{% trans "Forget password" %}-->
      <!--</a>-->
      <!--</div>-->
      <!--</div>-->

      <!-- Sign in button -->
      <button name="loginBtn" class="btn btn-blue btn-block my-4" type="submit">
        Sign in
      </button>

      <!-- Register -->
      <p>
        Not a member?
        <a href="{% url 'Users:signup'%}">Register</a>
      </p>

      <!-- Register -->
      <p>
        <a href="{% url 'Users:password_reset_request' %}">
          <div class="">Forget Password</div>
        </a>
      </p>
    </form>
    <!-- Default form login -->
  </div>
</div>
<!-- </div> -->
<br /><br />
{% endblock content %}

src/Users/templates/password_reset_request.html
{% extends "includes/base_user.html" %} {% load i18n %} {% load static %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="ui dividing header">{% trans "Forget Password" %} </h2>

            <form method="post">
                {% csrf_token %}
                {{ form.email }}
                {% if form.email.errors %}
                <div class="ui red message">{{ form.email.errors }}</div>
                {% endif %}

                <div class="d-flex justify-content-around">
                    <div>
                        <button class="btn btn-primary submit " name="resetBtn" type="submit">{% trans "Submit" %}
                        </button>
                    </div>
                    <div>
                        <a href="{% url 'Users:login'%}">
                            <div class="btn btn-default">{% trans "Cancel" %} </div>
                        </a>
                    </div>
                </div>


            </form>
        </div>

    </div>
</div>
<br>
<br>

{% endblock content %}

src/Users/templates/reset_change_password.html
{% extends "includes/base_user.html" %} {% load i18n %} {% load static %} {% block document_container %}
    <h2 class="ui dividing header">{% trans "Set new password" %}</h2>

    <form method="post">
        {% csrf_token %}
        <div class="ui two column middle aligned very relaxed stackable grid">
            <div class="column">
                <div class="ui form">
                    <div class="field">
                        <label>{% trans "Password" %} </label>
                        <div class="ui left icon input">
                            {{ form.password1 }}
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    <div class="field">
                        <label>{% trans "Confirm Password" %} </label>
                        <div class="ui left icon input">
                            {{ form.password2 }}
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="ui red message">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                    <button class="ui blue submit button" name="resetBtn" type="submit">{% trans "Submit" %}</button>
                    <a href="{% url 'Users:login'%}"><div class="ui button">{% trans "Cancel" %}</div></a>
                </div>
            </div>
        </div>
    </form>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


{% endblock document_container %}

src/Users/templates/signup.html
{% extends "includes/base_user.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<br><br>
<div class="row">
    <div class="col-md-6 offset-md-3">


        <!-- Default form register -->
        <form class="text-center border border-light p-5" method="post" style="background: white;">
            {% csrf_token %}

            {% for field in form %}
            <p>
                {% if forloop.counter == 1 %}

                <p class="text-left">ชื่อนามสกุล / รหัสผ่าน</p>
                <hr>
                {% endif%}
                {% if forloop.counter == 6 %}

                <p class="text-left">รหัสพนักงาน</p>
                <hr>
                {% endif%}
                {% if forloop.counter == 7 %}

                <p class="text-left">ข้อมูลติดต่อ</p>
                <hr>
                {% endif%}
                {% if forloop.counter == 9 %}

                <p class="text-left">ประเภทผู้ใช้งาน</p>
                <hr>
                {% endif%}
                {% if forloop.counter == 10 %}

                <p class="text-left">กรณีลืมรหัสผ่าน</p>
                <hr>
                {% endif%}

                {{ field }}
                {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
            {% endfor %}
            <br>
            <!-- Sign up button -->
            <div class="col-sm-6 offset-2">
                <button class="btn btn-blue my-4 btn-block " name="registerbtn" type="submit">ยืนยันการสมัคร</button>
            </div>
        </form>
        <!-- Default form register -->
    </div>
</div>
<br><br>
{% endblock content %}

src/Users/templates/status_message.html
{% extends "includes/base_user.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<meta http-equiv="refresh" content="{{ displaytime }};url={{ goto }}">
<div class="container" style="margin-top:25%" style="background:white;">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="text-center border border-light p-5">

                <h1>{% trans "System message" %} </h1>


                <div class="ui {{ type }} message">
                    {# <i class="close icon"></i>#}
                    <div class="header">
                        {{ message_header }}
                    </div>
                    <h3>{{ message_detail }}</h3>
                </div>
                     <div class="load-container load6"><div class="loader">Loading...</div></div>
            </div>
        </div>
    </div>
</div>
<div class="container" style="margin-top:20%">

</div>

{% endblock content %}