src/BaseSettings/urls.py
from django.conf.urls import url ,include

from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('Users/', include(('Users.urls','Users'), namespace='Users')),
    path('',include('SmsBaseApp.urls')),
    path('Team/' , include('Team.urls')),
    path('SmsBackEnd/', include(('SmsBackEnd.urls','SmsBackEnd'), namespace='SmsBackEnd')),
]

src/SmsBaseApp/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views import index,status_message

app_name = 'SmsBaseApp'

# set url with function in view SmsBaseApp
urlpatterns = [
    path('', index),
    path('SmsBaseApp/home', index, name='home'),
    path('SmsBaseApp/status_message', status_message),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

src/Team/urls.py
from django.urls import include, path, re_path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views_attachment import *
from .views_member import *
from .views_permission import *
from .views import *

app_name = "Team"
# set name url with function in views  manage user
urlpatterns = [
    path("show_team_all/", show_team_all, name="show_team_all"),
    path("show_team_page/", show_team_page, name="show_team_page"),
    path("create_team/", create_team_page, name="create_team"),
    path("create_team_save/", create_team, name="create_team_save"),
    path("add_member_page/", add_member_page, name="add_member_page"),
    path("add_member/", add_member, name="add_member"),
    path(
        "delete_member_from_id_role/",
        delete_member_from_id_role,
        name="delete_member_from_id_role",
    ),
    path(
        "show_member_list_by_team/",
        show_member_list_by_team,
        name="show_member_list_by_team",
    ),
    path("add_attachment_page/", add_attachment_page, name="add_attachment_page"),
    path("add_attachment/", add_attachment, name="add_attachment"),
    path("show_attachments/", show_attachments, name="show_attachments"),
    path("delete_attachment/", delete_attachment, name="delete_attachment"),
    path("add_permission_page/", add_permission_page, name="add_permission_page"),
    path("add_permission/", add_permission, name="add_permission"),
    path("show_permissions/", show_permissions, name="show_permissions"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

src/Users/urls.py
from django.urls import include, path,re_path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .views_users_admin import *
app_name = 'Users'

#set name url with function in views  manage user

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('status_message/', status_message, name='status_message'),
    path('admin_create_user_page/', admin_create_user_page, name='admin_create_user_page'),
    path('admin_create_user/', create_new_user, name='create_new_user'),
    path('user_all/', user_all, name='user_all'),

    re_path(r'^user/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate_account, name='activate_account'),
    re_path(r'^user/reset/password/request/$', password_reset_request,name='password_reset_request'),
    re_path(r'^user/reset/password/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<date>[0-9A-Za-z_\-]+)/(?P<time>[0-9A-Za-z_\-]+)/$',activate_password_reset, name='activate_password_reset'),
    re_path(r'^user/reset/password/change/$', reset_change_password_request,name='reset_change_password'),
    re_path(r'^user/change_password/$', change_password,name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

src/SmsBaseApp/views.py
from __future__ import unicode_literals
from django.http import HttpResponse
from django.template import loader
from django.db import connection
from django.template.loader import get_template
from django.template import Context
import subprocess
import shlex
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from rolepermissions.checkers import has_permission
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate
from django.db.models import Max
# from SmsBackEnd.helper import dictfetchall
from PIL import Image
# from SmsBackEnd.helper import *


# Home page
# @login_required(login_url="/Users/login/")
def index(request):
    try:
        group = Group.objects.get(name="user")
        return render(request, "home_page.html", {})
    except Exception as a:
        print("line 26", a)
        return render(request, "home_page.html")


# Status message
def status_message(request):
    args = {}

    try:
        args["goto"] = request.session["goto"]
        sm_value = request.session["sm_value"]
        args["type"] = sm_value["type"]
        args["message_header"] = sm_value["message_header"]
        args["message_detail"] = sm_value["message_detail"]

        del request.session["goto"]
        del request.session["sm_value"]

        return render(request, "status_message.html", args)

    except KeyError:

        return redirect("/SmsBaseApp/home/")


src/SmsBaseApp/templates/includes/base_other.html
<!DOCTYPE html>
{% load static i18n %} {% load i18n %} {% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>SmsBaseApp</title>
    <!-- Font Awesome -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
        integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Flag ICON-->
    <link href="{% static 'css/flag-icon.css' %}" rel="stylesheet">
    <link href="{% static 'css/docs.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Calendar -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.css" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.css" />  -->

</head>
<header>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand" href="{% url 'SmsBaseApp:home'%}">
                <strong>SmsBaseApp</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>

            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'SmsBaseApp:home' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'SmsBaseApp:about'%}">About</a>
                    </li>
         
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'SmsBaseApp:news_event'%}">News &
                            Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'SmsBaseApp:contact'%}">Contact
                            us</a>
                    </li>
                </ul>

                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        <a href="https://www.facebook.com/mdbootstrap" class="nav-link" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://twitter.com/MDBootstrap" class="nav-link" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a href="{% url 'Users:logout' %}" class="nav-link border border-light rounded">
                            <i class="fas fa-sign-in-alt"></i> Sign out
                        </a>

                        {% else %}
                        <a href="{% url 'Users:login' %}" class="nav-link border border-light rounded">
                            <i class="fas fa-sign-in-alt"></i> Sign in
                        </a>
                        {% endif %}
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle waves-effect waves-light" id="navbarDropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">TH
                        </a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item waves-effect waves-light"><i
                                    class="fab fa-pagelines fa-1x green-text"></i> TH</a>
                            <a class="dropdown-item waves-effect waves-light"><i
                                    class="fas fa-diagnoses fa-1x black-text"></i> EN
                            </a>

                        </div>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->

</header>






<!-- Block banner -->
{% block banner %}

{% endblock banner %}
<!-- End block banner -->
<!--<div class="container first-margin">-->
<!--<div class="bs-example " style="margin:0px">-->
<!--<ul class="breadcrumb">-->
<!--<li><a href="{% url 'SmsBaseApp:home' %}">Home</a></li>-->
<!--{% if url_first_level != nil and url_second_level == nil and url_third_level == nil%}-->
<!--<li class="active">{{ url_first_level }}</li>-->
<!--{% else %}-->
<!--<li><a href="">{{ url_first_level }}</a></li>-->
<!--{% endif %}-->
<!--{% if url_second_level != nil and url_third_level == nil  %}-->
<!--<li class="active">{{ url_second_level }}</li>-->
<!--{% else %}-->
<!--<li><a href="">{{ url_second_level }}</a></li>-->
<!--{% endif %}-->
<!--{% if url_third_level %}-->
<!--<li class="active">{{ url_third_level }}</li>-->
<!--{% endif %}-->
<!--</ul>-->
<!--</div>-->
<!--</div>-->
<!-- Block body -->
{% block document_body %}


<div class="container first-margin">
    <ol class="breadcrumb white z-depth-1">
        <li class="breadcrumb-item">
            <a href="/">Home Page</a>
        </li>
        <li class="breadcrumb-item">
            <a href="/support">Support forum</a>
        </li>
        <li class="breadcrumb-item">
            <a href="/support/cat/angular">Angular</a>
        </li>
        <li class="breadcrumb-item active">
            Card headers broken </li>
    </ol>
</div>
<!-- Block Container -->
{% block document_container %}



{% endblock document_container %}
<!-- End Block container -->

<!--Section: Logotypes-->
<section class="mt-4" style="background-color:#EEEEEE;height:80px;">
    <div class="container" style="height:80px;">


        <!-- Logo carousel -->
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="3600"
            style=" height: 6vh;">
            <div class="carousel-inner" style="height:80px;padding: 11px;">
                <!-- First slide -->
                <div class="carousel-item active">
                    <!--Grid row-->
                    <div class="row">

                        <!--First column-->
                        <div class="col-lg-2 col-md-6 text-center align-items-center justify-content-center">
                            <img src="{% static 'img/credit/bedo.png'%}" class="img-fluid px-4" alt="Nike - logo"
                                style="max-height: 60px">
                        </div>
                        <!--/First column-->

                        <!--Second column-->
                        <div class="col-lg-2 col-md-6 text-center align-items-center justify-content-center">
                            <img src="{% static 'img/credit/bkf.png'%}" class="img-fluid px-4" alt="Amazon - logo"
                                style="max-height: 60px">
                        </div>
                        <!--/Second column-->

                        <!--Third column-->
                        <div class="col-lg-2 col-md-6 text-center align-items-center justify-content-center">
                            <img src="{% static 'img/credit/forest.png'%}" class="img-fluid px-4" alt="Sony - logo"
                                style="max-height: 60px">
                        </div>
                        <!--/Third column-->

                        <!--Fourth column-->
                        <div class="col-lg-2 col-md-6 text-center align-items-center justify-content-center">
                            <img src="{% static 'img/credit/kku.png'%}" class="img-fluid px-4" alt="Samsung - logo"
                                style="max-height: 60px">
                        </div>
                        <!--/Fourth column-->
                        <!--Fourth column-->
                        <div class="col-lg-2 col-md-6 text-center align-items-center justify-content-center">
                            <img src="{% static 'img/credit/lanna.png'%}" class="img-fluid px-4" alt="Samsung - logo"
                                style="max-height: 60px">
                        </div>
                        <!--/Fourth column-->
                        <!--Fourth column-->
                        <div class="col-lg-2 col-md-6 text-center align-items-center justify-content-center">
                            <img src="{% static 'img/credit/ricedept.png'%}" class="img-fluid px-4" alt="Samsung - logo"
                                style="max-height: 60px">
                        </div>
                        <!--/Fourth column-->


                    </div>
                    <!--/Grid row-->
                </div>
                <!-- First slide -->


            </div>
        </div>
        <!-- Logo carousel -->
    </div>
</section>
<!--/Section: Logotypes-->



<!--Footer-->
<footer class="page-footer text-center font-small  wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">

    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus mr-3"></i>
        </a>

        <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a>

        <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2018 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->
</footer>
<!--/.Footer-->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->

<!-- calendar -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>

<script>
   $(document).ready(function() {
   var calendar = $('#calendar').fullCalendar({
    header:{
     left:'prev,next today',
     center:'title',
     right:'month,agendaWeek,agendaDay'
    },
    events: '/SmsBackEnd/load_events/',
        });
    });
</script>


</footer>

{% block script %}


{% endblock script %}
<!-- End block unique -->

<!-- End block body -->
{% endblock document_body %}
</body>

</html>